### ISSUE TITLE
fail with Julia last release (1.10.3)

### ISSUE THREAD

**Issue by pjbarjhoux** [worlddynamics/Earth4All.jl#17]
Hi,

First of all, many thanks for this Julia Earth4All implementation,
This issue is a feedback concerning installation procedure and Julia compatible version.

As I am new to Julia, I had to install Julia at first,
I downloaded last release (1.10.3) as described in Julialang website but I got some errors during dependencies installation, based on both master branch and E4A tag 0.1.0.

I had to install Julia 1.9.0 as follows (note : macOS system) :

1.  install last Julia version :
`curl -fsSL https://install.julialang.org | sh`

3. install specific 1.9.0 Julia version :
`juliaup add 1.9.0`

4. and then specify the version when starting Julia REPL :
`juliaup +1.9.0`

5. follow E4A procedure in the documentation (instantiate environment and so on)

Did I miss something?
Also I had to install both 1.10 and 1.9, not sure this is the best way to proceed.
Note that it worked based on E4A tag 0.1.0, but failed on main branch

As a suggestion I think this may be useful for new users (and new Julia users like me!) to mention the Julia compatible version on the README file.

**Comment by aurorarossi** [comment]
Hello!
Probably a problem on our side!
Can you try to delete the `Manifest.toml` file from the repository and try again using Julia 1.10.3 to activate and instantiate the environment and tell me if it works for you?
Thanks for pointing this out!

**Comment by aurorarossi** [comment]
Great! I will close the issue and update the repository removing it.
Thanks again!
